apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backstage-showcase
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ktsao-tenant/backstage-showcase/backstage-showcase@sha256:d04f51495418870d0cddd2a2b4c060b3596d6a82146f337e1aa4b6e8a8f1d704
        name: container-image
        resources: {}
status: {}
