apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backstage-showcase
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ktsao-tenant/backstage-showcase/backstage-showcase@sha256:bbe73d44f0651591eee2503747ebd47631a741c5de747fbd6285df198ae2b799
        name: container-image
        resources: {}
status: {}
