apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backstage-showcase
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backstage-showcase
    app.kubernetes.io/part-of: backstage-showcase
  name: backstage-showcasexlxk
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backstage-showcase
    weight: 100
status: {}
